version: '3.1'

services:

  home.storage:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    volumes:
      - ./volumes/store:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password

  home.mariaDb:
    # (in) 3306
    image: mariadb:latest
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password


  home.mySql:
    # (in) 3306
    image: mysql:latest
    ports:
      - "3320:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

  home.pma:
    image: phpmyadmin
#    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1